version: '3.3'

volumes:
  postgres-data:
  redis-data:

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  app:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/app_db
      REDIS_URL: redis://redis:6379
    ports:
      - 8000:8000
    volumes:
      - .:/app